### PR TITLE
Fix mistypes and error calls

### PR DESCRIPTION
**Pull request by kostikvento**
Fix mistypes and error calls

1. Got `NameError` in `core.envelope` and `core.track.send`  because `reapy` was not imported there, so I decided to use `Program` to let it work without importing. (I've checked manually that it works now).
2. Didn't find any mention about `DistProgram` through the whole codebase, neither any magic which would allow `DistProgram` to be found inside `tools.dist_program`. I believe it was just a mistype during adding `tools.dist_program.Program` instead of `DistFunc`, so I fixed it.
3. The rest are obvious mistypes.

### CODE REVIEW

**Comment by RomeoDespres** [comment]
Thanks! About your 1., I'm just wondering why not add `import reapy` at the beginning of `core.envelope` instead of using a `Program`? The rest seems good!

**Comment by kostikvento** [comment]
I simplified the fix in `envelope` and `send`.

I also suggest use this way to get `RPR`:

```
import reapy
RPR = reapy.reascript_api
```

rather than doing double imports.

**Comment by RomeoDespres** [comment]
Thanks, I believe it's cleaner that way.

I was doubtful about the readability of your suggestion about `RPR`, since I've never really seen this kind of module-renaming before. I have asked the question on StackOverflow [here](https://stackoverflow.com/questions/56557529/python-best-practice-how-to-alias-a-module), and people seem to agree with my intuition. Especially, one comment says that the syntax `import ... as ...` would maybe not exist if best practice was to manually rename modules. I'd thus say it is better to go back to the previous versions (`from reapy import reascript_api as RPR` or `import reapy.reascript_api as RPR`).

**Comment by kostikvento** [comment]
Well, the only reason why I suggest to do so is to avoid unnecessary doubling import machinery for `reascript_api` since it **has already been** imported in `reapy.__init__` and can be referenced to as `reapy.reascript_api`. If it would not have been imported there, then `from reapy import reascript_api as RPR` would be obviously the right way.

Anyway, if you think that importing `reascript_api` twice (in `reapy.__init__` and after via `from reapy import reascript_api `) is still good, I'm okay to revert it.

**Comment by RomeoDespres** [comment]
`timeit` tests:

```bash
$ python -m timeit -s "import reapy" "RPR = reapy.reascript_api"
10000000 loops, best of 3: 0.0303 usec per loop
$ python3.5 -m timeit -s "import reapy" "import reapy.reascript_api as RPR"
1000000 loops, best of 3: 0.661 usec per loop
```

So indeed the second way is around 20 times slower. Yet it's a very small overhead of 0.6 micro-seconds. In my opinion, the benefit of having more readable imports that are consistent with standard Python usage exceeds this additional start-up time.

**Comment by kostikvento** [comment]
Ok, I rebased all fixes into single commit.

**Comment by RomeoDespres** [comment]
Great thanks!

**Pull request merged**
