### PR TITLE
small useful things

### PR DESCRIPTION
**Pull request by kostikvento**
This is to fix issue https://github.com/RomeoDespres/reapy/issues/7

Reviewing commit-by-commit is advised, since the commits are grouped by problems solved.

### CODE REVIEW

**Comment by kostikvento** [comment]
`docs/source/py2_issues.rst` is for historical reasons, it seems to be outdated and incomplete now that the work is done, I can remove it before merging

**Comment by RomeoDespres** [comment]
Sorry I have not reviewed this contribution earlier, but it is quite a big piece and raises many questions, so I takes me some time!

Here is a first question: I don't understand why you say `reapy.print` can't be used as it is. I believe in Python >= 2.7, the following is valid:

```python
>>> from __future__ import print_function
>>> _ORIGINAL_PRINT = print
>>> def print(*args, **kwargs):  # prints twice
...     _ORIGINAL_PRINT(*args, **kwargs)
...     _ORIGINAL_PRINT(*args, **kwargs)
... 
>>> print('a', 'b', sep='foo', end='bar\n')
afoobbar
afoobbar
```

`print` is no more reserved once `from __future__ import print_function` has been stated.

**Comment by kostikvento** [comment]
> `print` is no more reserved once from `__future__ import print_function` has been stated.

That's true, I seem to have missed this out(
I'll revert this part then.

**Comment by RomeoDespres** [comment]
Last two commits are fine thanks! Not sure that the first one (constants `reapy.PY2` and `reapy.DEBUG`) makes much sense without Python 2 support

**Pull request merged**
