### PR TITLE
Add SWS support

### PR DESCRIPTION
**Pull request by chabErch**
Issue #15 
Added support for using SWS functions in reascript_api.
If the SWS extension has not been installed, then nothing breaks.

### CODE REVIEW

**Comment by RomeoDespres** [comment]
Thanks, it's definitely a good idea to include SWS extension in the API! Yet I wonder whether the module structure obtained is the best. Does it make sense to include the SWS extension inside the `reascript_api` module? Wouldn't it be best to have a new `sws_api`, or `sws` module ? In that case people would be able to specifically import it when they need it, and we could raise a `ModuleNotFoundError` if it is not installed.

Also, being unable to access my REAPER computer for now, I am not entirely sure whether your commit allows running SWS functions from outside REAPER or not. Could you please confirm that? If not, for the consistency of the whole API, wouldn't it be best to merge into `master` only when distant imports of the SWS extension is implemented?

**Comment by chabErch** [comment]
I think sws should be inside reascript_api. For the user, it should not matter where the function comes from. However, if sws is planned to be used in "reapy.core" then it is necessary to require the user to pre-install sws.

SWS functions are available both inside and outside the Reaper.

api_test
api_test

**Comment by RomeoDespres** [comment]
I've been testing it on my own and having a problem when using `from reapy.reascript_api import *` from *inside* REAPER, which results in the following error:
```
Script execution error

Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from reapy.reascript_api import *
AttributeError: module 'reapy.reascript_api' has no attribute 'ReaPack_AboutInstalledPackage'
```

Note that all works fine from outside REAPER. It seems like the `__all__` variable defined on line 20 is no longer correctly defined when SWS is installed. I think we should find a workaround before merging that. At least, do you also have the bug?

**Comment by RomeoDespres** [comment]
Apart from that, it's great that it works inside and outside REAPER with such a simple change!

**Comment by chabErch** [comment]
Everything works fine for me. And I do not know how to reproduce the error to correct it.

from_rescript_import

**Comment by chabErch** [comment]
Maybe this is a conflict with ReaPack. I will try to install it and reproduce the error.

**Comment by RomeoDespres** [comment]
Oh ok. So the bug was already there, and is not linked to your contribution, sorry!

**Comment by RomeoDespres** [comment]
I merge your contribution into the new branch feature/api-extension-support, so that I can handle the mentioned bug before it gets into master. Thanks for your time!

**Pull request merged**
