### PR TITLE
Added midi info and receives property

### PR DESCRIPTION
**Pull request by Levitanus**
let's start within this and look what we want in the future

### CODE REVIEW

**Comment by Levitanus** [comment]
Yes, here is SWS API, so it's discussble question. For example, I can't make cheap python binding to the JS_ReascriptAPI extension on my PC. On Linux sws_python also made only from source (which is not as noob task as `make install`).

But, considering reapy installation, maybe it's not so destructive to keep sws bindings inside the library, through later it can lead to the high-level type-safe abstractions.

Anyway, this pull-request is still alive (I mean, open for updates), and I want to see where it can lead, but I'm able to continue only at the end of the week.

**Comment by RomeoDespres** [comment]
Yeah I was also wondering why the ReaScript API would allow us to know the source track of a Send but not the target track... Doesn't make much sense right? So thanks for adding this!

About the SWS dependency: since SWS is not installed via `pip`, it is not possible to explicity state it as a `reapy` dependency. Thus I thought we could add a custom error that would be raised on SWS-dependent functions when SWS is not installed. Something like:

(in /reapy/errors.py)
```python
class ExtensionNotFoundError(Exception):

    def __init__(self, extension, url):
        message = (
            "Extension {} is required by this function but is not available. "
            "Please install it from {}."
        ).format(extension, url)
        super().__init__(message)
```

and then for instance in `get_infos_br` (btw, wouldn't `get_sws_infos` be more clear?):

```python
try:
    return RPR.BR_GetSetTrackSendInfo(
        self.track_id, self._get_int_type(),
        self.index, param_name, False, 0.0
    )
except AttributeError:
    raise ExtensionNotFoundError('SWS', 'www.sws-extension.org')
```

As in the other PR, you can grant me permission to commit to this PR so that I add these features myself if you like ([doc here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)).

**Comment by Levitanus** [comment]
> Yeah I was also wondering why the ReaScript API would allow us to know the source track of a Send but not the target track...

Just found: bad docs.
```I_MIDIFLAGS : int *, low 5 bits=source channel 0=all, 1-16,
                                next 5 bits=dest channel, 0=orig,
                                1-16=chanP_DESTTRACK : read only, 
                                returns MediaTrack *,
                                destination track,
                                only applies for sends/recvs```
read carefully)

**Comment by RomeoDespres** [comment]
hmmmm interesting... well done for spotting that! Maybe there is something to do here without using SWS!

**Comment by Levitanus** [comment]
> you can grant me permission to commit to this PR

It's turned on by defauld, feel free, I'm dead for today...

**Comment by RomeoDespres** [comment]
ok thanks! Yeah me too (probably quite earlier at my place than yours but still I'll take a look at that another day!)

**Comment by Levitanus** [comment]
Great work!

As I understand, SWS API is also somehow wrapped around original. But in the particular case with send midi info — I feel something missing, considering BUS destination. If believe docs: 

> I_MIDIFLAGS : returns int *, low 5 bits=source channel 0=all, 1-16, next 5 bits=dest channel, 0=orig, 1-16=chanSee 

There no place for BUS. But SWS got them somwhere...

**Comment by Levitanus** [comment]
I've detached Introduces properties from the sws, leaving the `extension_dependensy` untouched. So, basically, now it should be quite stable)

**Comment by nofishonfriday** [comment]
@Levitanus 
>As I understand, SWS API is also somehow wrapped around original. But in the particular case with send midi info — I feel something missing, considering BUS destination. If believe docs

Here's the function SWS is using:
https://github.com/reaper-oss/sws/blob/430602a9aa5fb8cbaa145ca9415efb57a3919013/Breeder/BR_ReaScript.cpp#L524

From the comments:
// source MIDI bus is bits 14-21
// destination MIDI bus is bits 22-29

I don't know why but this seems indeed be missing in the docs.
Hope it helps.

**Comment by Levitanus** [comment]
@nofishonfriday Thanks! But yet works here:
https://github.com/RomeoDespres/reapy/pull/56/commits/ef14d86f10d6183f621688c92aa068f6951cd355

**Comment by RomeoDespres** [comment]
Thanks a lot for taking care of the unnecessary SWS dependencies, now this looks all clean to me!

**Pull request merged**
