### PR TITLE
fix: correct adding note in Take.add_note

### PR DESCRIPTION
**Pull request by kostikvento**
1. replace `start`/`end` rather than assigning values to tuple items
 (the latter is impossible moreover)
2. fix calculating `start`/`end` with unit=beats
 (wouldn't convert non-zero values properly)

### CODE REVIEW

**Comment by RomeoDespres** [comment]
Thanks! Could you move all the code for `take.add_note` in a `Program`, so that only one distant call is required to run the function? For now a handful of them are needed, which uselessly slows down execution.

**Comment by kostikvento** [comment]
I propose a solution (https://github.com/RomeoDespres/reapy/pull/27/commits/27609a2ab1b702b36f1a340c0ceb9bbc282c4d06) which keeps code inspectable, easy to read and less mistype-prone while requiring just one distant call as you requested. Moreover, it makes calling this method within Reaper scripts/actions even faster because there's no overhead to wrap code in `Program(code).run` (which is unnecessary inside Reaper).

**Comment by RomeoDespres** [comment]
This seems very nice actually. I would like to test it a little bit before merging, because if it really works better than `Program(code)`, we could maybe reuse it in the whole code base... as it clearly is more elegant

**Comment by kostikvento** [comment]
I decided to separate fixing `add_note` and developing `run_inside` decorator. The latter is in https://github.com/RomeoDespres/reapy/pull/30, so you can merge this PR to fix `Take.add_note` (I've moved code back under Program as you requested).

**Comment by RomeoDespres** [comment]
That makes total sense, thanks!

**Pull request merged**
