### PR TITLE
Feature/project ext state

### PR DESCRIPTION
**Pull request by Levitanus**
During my own development I thought: "why not?" and decieded:

- No reascript_api usage without reapy wrap!

So... Another pull

### CODE REVIEW

**Comment by RomeoDespres** [comment]
Thanks, I remember looking at this ReaScript function and thinking "yet again one of these cryptic documentations... mmmh, maybe later". But you're right, it is a useful one! I do have a few ideas to improve your solution. If you are okay with it, would you allow me to commit to this pull request so that I can add them? ([How to do it](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork))

I can also explain them to you but it's probably gonna be easier and faster if I simply do it!

**Comment by Levitanus** [comment]
изображение
should be able already, thanks

**Comment by RomeoDespres** [comment]
Hey, just copying here the description of the main commit I made. I hope it's fine by you, feel free to comment if you feel something is wrong in it!

# Commit summary

## Pickling argument

Unify arguments `pickled` for `Project.get_ext_state` and `pickle_` for `Project.set_ext_state` into `pickled` for both.
I believe it simplifies the API to always use the same name for a similar argument.

## Limit on state value size

REAPER supports ext state values with a maximum length of `2**31 - 1`. Why limiting it to 100? Moreover, no need to store ext state size: always passing the maximum value of `2**31 - 1` is sufficient.

**Comment by Levitanus** [comment]
Thank You so much for my English. I can read 10 times and not see the problem...

##Considering the code changed
I think, my docstring was not clear: size calculated exactly, and stored in the 100*char bit representation e.g. (b00000000000000000<some size value>). It's much bigger size of data, than Reaper can store, but not the big problem for storing the size-string.

I afraid, that calling of GetProjExtState with the max size we can take not only the stored data. But I'm not sure how to check it. May it not going much far, than project allocated mem, but take other extension data

**Pull request merged**
