### PR TITLE
feat: context managers + decorators (prevent_ui_refresh, reaprint et al)

### PR DESCRIPTION
**Pull request by kostikvento**
All features in this pull request can be tried in a snippet of code like this:

```python
@reapy.inside_reaper()
@reapy.reaprint
@reapy.prevent_ui_refresh
@reapy.undo_block('add tracks')
def add_tracks(n):
    print('Adding', n, 'tracks')
    for x in range(n):
        reapy.Project().add_track()
        
add_tracks(100)

with undo_block('another undoable thing'):
    with reapy.prevent_ui_refresh:
        with reapy.reaprint:
            print('This could be an undoable action but console can't be cleared partially')
```

### CODE REVIEW

**Comment by RomeoDespres** [comment]
Thanks! A few comments:
- Having `inside_reaper`, `prevent_ui_refresh` ans `undo_block` as decorators makes perfect sense to me, they are great!
- I think `reapy.utils` is not a good idea since we already have `reapy.tools`, and it is where helpers like `ContextManagerDecorator` should be stored.
- But is it any useful? Why not employ the built-in [ContexDecorator](https://docs.python.org/3/library/contextlib.html#contextlib.ContextDecorator) instead?
- I'm not sure about the `reaprint` context manager. Is it really doing better than `reapy.print`? Quoting [PEP 20](https://www.python.org/dev/peps/pep-0020/), "there should be one-- and preferably only one --obvious way to do it", and it seems to me that those two functions are quite redundant. But if one has to be dropped, it probably can't be `reapy.print`, because it makes sense to have a function that prints to the console without needing a context manager, no? So what is the purpose of `reaprint` apart from saving a few characters by typing `print` instead of `reapy.print`?

**Comment by RomeoDespres** [comment]
Thanks! A few comments:
- Having `inside_reaper`, `prevent_ui_refresh` ans `undo_block` as decorators makes perfect sense to me, they are great!
- I think `reapy.utils` is not a good idea since we already have `reapy.tools`, and it is where helpers like `ContextManagerDecorator` should be stored.
- But is it any useful? Why not employ the built-in [ContexDecorator](https://docs.python.org/3/library/contextlib.html#contextlib.ContextDecorator) instead?
- I'm not sure about the `reaprint` context manager. Is it really doing better than `reapy.print`? Quoting [PEP 20](https://www.python.org/dev/peps/pep-0020/), "there should be one-- and preferably only one --obvious way to do it", and it seems to me that those two functions are quite redundant. But if one has to be dropped, it probably can't be `reapy.print`, because it makes sense to have a function that prints to the console without needing a context manager, no? So what is the purpose of `reaprint` apart from saving a few characters by typing `print` instead of `reapy.print`?

**Comment by RomeoDespres** [comment]
And by the way, I'm surprised that none of your contributions actually registers you as a contributor on the repo. I've done some research but all I've found is [this](https://www.quora.com/Why-doesnt-GitHub-include-my-name-as-a-contributor-even-after-I-contributed). Maybe you could try it? For now your commits seem to be attributed to no one...

**Comment by kostikvento** [comment]
I've changed my email for this repo, now it should work, I believe.

Now on you questions.

> I think `reapy.utils` is not a good idea since we already have `reapy.tools`, and it is where helpers like `ContextManagerDecorator` should be stored.

The reason to put them to separate folder is that I want them to be importable without importing things from `reapy.tools.__init__`. In Python 2 it leads to circular imports, that's why I also put `configparser2` (in Py2 pull request) right to `util`.

> But is it any useful? Why not employ the built-in `ContexDecorator` instead?

`ContexDecorator` is absent in Python 2.

> So what is the purpose of `reaprint` apart from saving a few characters by typing `print` instead of `reapy.print`

It is useful when you want to switch fast between printing to ReaperConsole and stdout (and helps not forget restoring original sys.stdout).
I see its usage e.g. when you test an external function and sometimes you want it to print to ReaperConsole, and sometimes (when Reaper hangs or performs slowly) you want to print things to stdout.
Another thing is that in Python 2 you can still use old syntax `print something` rather than `print(something)`. And if you need to print something to ReaperConsole, you'll have to replace all plain `print`s to `reapy.show_console_message`s (because `reapy.print` cannot be used in Py2).

**Comment by kostikvento** [comment]
> it makes sense to have a function that prints to the console without needing a context manager

There is already `reapy.show_console_message` for that ))

**Comment by kostikvento** [comment]
So what about this pull request? If you suppose that `reapy.reaprint` decorator is redundant, I can remove it from here (while still keep using it in my experimental branches since I find it rather useful).

**Comment by RomeoDespres** [comment]
Just added a small change in the naming of your classes:

When looking at [the doc for ContextDecorator](https://docs.python.org/3/library/contextlib.html#contextlib.ContextDecorator), all examples use lowercase, function-like names instead of class-like camel-case names. Though I haven't found a PEP rule for this, it seems a more elegant way to me than to define global instances as previously done. Indeed:
- global variables are generally considered bad practice if they are not constants
- the usual naming scheme for global variables is capital letters and underscores (see PEP 8). So if the reason for using a global variable instead of just changing the class name is to respect the usual naming scheme for classes, it results in breaking another usual naming scheme.

Also, I find it better if context managers have consistent behavior regarding brackets (i.e. better to use `reapy.reaprint()` than `reapy.reaprint` because in any case we need brackets for `reapy.undo_block`). And examples in the doc all use brackets so I think it's more consistent this way.

Everything is fine for me now, if it's also fine by you!

**Comment by kostikvento** [comment]
It's all fine for me:
- I do agree that it's really simpler to define lowercase classes and not define instances (it's just that I have used to camel-case class names so much); the more so that the docs allow lowercase classes;
- the brackets are fine for consistency; it's just my habit to (sometimes over)optimize code :-)

P.S. Special thanks for letting `reaprint` live in the official branch :-)

**Pull request merged**
