### PR TITLE
Take extended

### PR DESCRIPTION
**Pull request by Levitanus**
Still are problems with midi functions, but something is better to include

### CODE REVIEW

**Comment by Levitanus** [comment]
The last commit demonstrates possibility of self-fixing the original API.

Here is example of getting correct midi event.
```Python
import reapy as rpr
from reapy import additional_api as APR

take = rpr.Project().items[0].active_take
result = APR.MIDI_GetEvt(take.id, 0, 0, 0, 0, 'msg', 300)[6]
rpr.print(list([f'{ord(i)} ({hex(ord(i))})' for i in result]))
```
изображение


Time to think of wrapping it better.

**Comment by Levitanus** [comment]
Well it should be quite OK, a lot of good stuff done, major part ought to be made.
But, still, can be merged.

**Comment by RomeoDespres** [comment]
I like the idea of fixing ReaScript API bugs within reapy as you did. However with the way it is currently implemented, it doesn't work from outside REAPER:

```python
>>> import reapy.additional_api
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name '_RPR' from 'reapy.reascript_api'
```
This is because C bindings only work from inside REAPER. We should think of a general solution for this. It could also be used to fix the problem of `RPR_GetTrackSendInfo_Value` returning pointers instead of ReaScript IDs.

**Comment by Levitanus** [comment]
Sorry, the example is outdated.
Now all functions are available from the `reapy.reascript_api`
look to the take.py changes as for example :)

**Comment by RomeoDespres** [comment]
Ah I see, so `additional_api` is only intended for internal use, but should not be imported by the user. This is nice! What about all these commented out functions, is there a reason why you kept them?

**Comment by RomeoDespres** [comment]
In `Take.add_event`, you wrote in docs:

> For a long time inserting a notes within this function caused problems. Better to use the proper function for that.

What do you mean by that exactly? And what is the "proper function"?

**Comment by Levitanus** [comment]
>  is there a reason why you kept them?
I'm not sure what is broken, as not the whole part is wrapped yet. I just want to see, what else is available as a diff-view.

**Comment by RomeoDespres** [comment]
> I'm not sure what is broken, as not the whole part is wrapped yet. I just want to see, what else is available as a diff-view.

Ok then I guess we can keep them for a while!

**Comment by Levitanus** [comment]
> What do you mean by that exactly?

hmm, Yes, it causes problems, as adding notes through `add_event` will make them very short anyway. It's still buggy behaviour, known as bug on the forum.
Yes, proper function is `add_note`. I'll fix docs now.

**Comment by RomeoDespres** [comment]
Haha no worries! I think we're good here anyway

**Pull request merged**
