### PR TITLE
Hotfixes

### PR DESCRIPTION
**Pull request by Levitanus**
Many of slight changes: stubs, errors handling etc.

### CODE REVIEW

**Comment by RomeoDespres** [comment]
Thank you a lot for all these fixes that are of great value.

I only have one concern about commit 
2c6d8a7 (track instantiation from the pointer). It is a useful feature because of `RPR_GetTrackSendInfo_Value` returning pointer instead of ReaScript ID, as you've noticed in [this comment](https://github.com/RomeoDespres/reapy/issues/59#issuecomment-603370887). However I don't think it should be part of reapy's API, since it is only useful *internally* to make things work inside the `Send` class. Thus I think the right option is to keep  `Track. _get_id_from_pointer`, so that we can use it in other parts of reapy, but to remove the bit that uses it in `Track.__init__`.

And for the sake of it, I just tried adding 10,000 tracks to a REAPER project to see if it can handle it, and it can! What a wonderful DAW. So the limit you hard-coded is not high enough!

If you're ok with that, I'll quickly take care of these fixes and then merge the whole branch.

**Comment by Levitanus** [comment]
> And for the sake of it, I just tried adding 10,000 tracks to a REAPER project to see if it can handle it, and it can! What a wonderful DAW. So the limit you hard-coded is not high enough! 

🤣 OK, newer thought it could be a case.

I'm not sure about disabling the checkup at the instantiation, as we never know where else API returns pointer. As we've met the case once — it can appear later.

**Comment by Levitanus** [comment]
I'm now totally bothered by the MIDI_* part of API, and it sucks... Glad to see you here again and hope for a fresh view.

**Comment by RomeoDespres** [comment]
I mean... returning pointers instead of IDs seems like a bug of ReaScript. So I'd rather notice it because it doesn't work, and manually fix it by using Track._get_id_from_pointer, than not being aware of it. Sounds healthier to me. Maybe if this happens in a lot of functions, we can rediscuss this but for now, I think it should only be treated as a corner-case.

Yeah the MIDI part seemed really obscure... Which is why I haven't worked on it that much so far. And it's a shame because it's like one of the most basic stuff one wants to do with ReaScripts right?

And yeah it's been hard lately to do something here, with the lockdown my job has become very time-consuming... Anyway, in the next days I'll try to catch up on all the work you've been doing. It's great how you help the project expand and stabilize!

**Comment by Levitanus** [comment]
OK let's consider It the 'per-bug' way.

Thank You, hope lockdown will pass soon)

**Pull request merged**
