### PR TITLE
Feature/allow subclassing

### PR DESCRIPTION
**Pull request by Levitanus**
`reapy.core` classes able for subclassing, which should be done with caution:
    * considering this, `reapy.errors.SubclassedWarning` is added
    * TODO: documantation should mark the subclassing process

### CODE REVIEW

**Comment by Levitanus** [comment]
Hmm, I just thought, that `ImportError` should be sent back and do not activate reaper window with traceback.

**Comment by RomeoDespres** [comment]
I've already thought about this issue some time ago. Here are some concerns I have with your current implementation, from least to most troublesome:

1. `__init_subclass__` is only available for Python >= 3.6.
2. When using reapy from outside REAPER, it is unlikely that the current working directory (in which the user has their `ReapyObject` subclasses) is available in REAPER's `sys.path`. Thus, JSON decoding inside REAPER will still fail. A simple solution for that would be to send the outer `sys.path` during the connection process, so that working directory is systematically available inside REAPER too.
3. One of the main purposes of reapy is to allow usage of third-party library with REAPER. However, with your implementation, subclassing `ReapyObject` makes it impossible again, because the user's module (with its third-party dependencies) will be imported inside REAPER for decoding.

One alternative solution would be to only send the ReapyObject part over the network. This is not gonna be easy to implement tough, and I'm not sure it would work well in all cases.

Otherwise, we should officially stipulate that subclassing reapy objects is not possible, and send an error locally (instead of the current deferred script error, which is clearly undesired, and by the way, thanks for spotting it! 😃)

**Comment by Levitanus** [comment]
> `__init_subclass__` is only available for Python >= 3.6.

As I understand, nothing scary (instead of not auto-calling it) happens in 3.5, for example.
> the user has their ReapyObject subclasses) is available in REAPER's sys.path.

This is what the warning and error for: to point on this. `pip install <my_package> -e git_folder` makes it stable.

> One of the main purposes of reapy is to allow usage of third-party library with REAPER.

I didn't see the point for a long time, and finally, got: If user changed the code he has to change the Reaper instance....

But I really hate to write `some_dict[some_my_track.track.id].my_project.project.attribute`. It feels like... C++ :D

**Comment by RomeoDespres** [comment]
It's not just changing the code, but also simply having two different scripts that use the same library... If you import  third-party library inside REAPER more than once, it crashes. This is a serious issue for many users!

>
> It feels like... C++ :D

You are so right... Then maybe we should try to investigate the alternative solution I proposed. Because I really think the third-party issue is a blocking point.

**Comment by Levitanus** [comment]
> However, with your implementation, subclassing ReapyObject makes it impossible again, because the user's module (with its third-party dependencies) will be imported inside REAPER for decoding.

Can You provide example that crashes?
I've just tried:
```Python
# simple_test.py
import reapy as rpr


class Project(rpr.Project):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        print(self.name)
```
```Python
# simple_test2.py
from simple_test import Project


class Project2(Project):
    pass


print(Project2().name)
```
```
Output:
/home/levitanus/gits/reapy/reapy/core/reapy_object.py:12: SubclassedWarning: 
- By subclassing of reapy.core member by <class 'simple_test.Project'> You should consider that your object has to be able to rebuilt from scratch bycalling within usage of properties `_args` and `_kwargs`.
- Please, do not forget about super()
- Warning can be disabled for this class by subclassing within Class(Parent, subclassed=True) parameter.
  warn(reapy.errors.SubclassedWarning(str(cls)))
/home/levitanus/gits/reapy/reapy/core/reapy_object.py:12: SubclassedWarning: 
- By subclassing of reapy.core member by <class '__main__.Project2'> You should consider that your object has to be able to rebuilt from scratch bycalling within usage of properties `_args` and `_kwargs`.
- Please, do not forget about super()
- Warning can be disabled for this class by subclassing within Class(Parent, subclassed=True) parameter.
  warn(reapy.errors.SubclassedWarning(str(cls)))
test_master.RPP
test_master.RPP
[Finished in 0.4s]
```

**Comment by RomeoDespres** [comment]
Hmm... first, `random` is not a third-party library but is part of the standard library, which does not crash REAPER. Bugs occur when you start importing `numpy`, `requests`, etc.

Now, you made me realize that your implementation will not crash REAPER on its own, because to crash it, you have to instantiate two ReaScripts that both import the same third party library. However in the case of reapy, there is only one ReaScript ran inside REAPER: `activate_reapy_server.py`. So theoretically, no worries.

I'm a bit uncomfortable though with the fact that we're basically saying "ok, there can only be one import of third-party library, well reapy is taking it!", because what if another script needs it? Plus, we're definitely relying on a buggy feature there.

But still, it should work. Sorry about that mistake! I'd like to think more about it, if it's okay with you, because it's really a core feature and I don't want to mess anything up there.

**Comment by Levitanus** [comment]
OF course! Take your time. I will think on the way too.

**Comment by Levitanus** [comment]
Also, possible solution (The hard way) — as I thought at first — use of metaclass. The general concept is to make some sort of descriptor behavior for all the reapy classes attributes.
In this case the real reapy part is executed inside while subclasses are executed as third-party libraries.
I have experience in making such mechanic, but than I've made some core mistakes and the whole system became inexpressive.

Maybe there is a point to make analogue of __slots__ that can be used by the core members.

**Comment by RomeoDespres** [comment]
Thanks for the metaclass suggestion, I've tried to write something based on it (#68).

An additional potential problem I've thought about with the implementation here: what if the user's modules that contain the subclasses have side-effect on import? This is not a good practice but can happen in some cases (actually reapy has some!). Re-importing inside REAPER may be troublesome in that case.

**Comment by Levitanus** [comment]
> Re-importing inside REAPER may be troublesome in that case.

This is where new issue happens. But, actually, maybe it leads to the clean code. Opposite to the couple-months ago, reapy now can be imported in much more wide range of cases :)

**Comment by RomeoDespres** [comment]
Haha you're right! Ok, thanks for all the work and discussion :) I'll close this one and merge the other one then.

**Pull request closed without merging**
