### PR TITLE
Hotfixes

### PR DESCRIPTION
**Pull request by Levitanus**
Occasionally, I've mistaken in `Project.set_info_value`, in docs there was talk about 'null'...

### CODE REVIEW

**Comment by Levitanus** [comment]
Despite the last commit introduces new API, conceptually it is more like hotfix, as the functionality is quite core.

**Comment by RomeoDespres** [comment]
Hey, thanks for all this and especially the fix for issues #62 and #80! It's really, really cool to have this major bug fixed. I'll review the remaining commits later and merge it all.

**Comment by Levitanus** [comment]
May I object making `validate_id` private?

Project here is not an object to check of, but the object to check within (if track exists in project) :)

This is one of cases for which original `RPR_ValidatePtr` was designed for: to check whether object exists inside Reaper. And, for example, I already need to know whether my Project object is valid or not, because lifecycle of my script is wider, than one Reaper session and one Reaper instance)
In simpler cases objects are being removed, renamed etc without lettig script know about that, so, why not to leave this wrap of original api? as is?

Maybe my docstring was bad.

**Comment by RomeoDespres** [comment]
Ok I see your point, sometimes we need to check for an object's validity. However I still think it should be a property of the object: in the case of tracks, we should be able to use `Track.has_valid_id`. And `ValidatePtr2` is currently broken, so a fix has to be included to make your implementation of `validate_id` work for non-project objects. Let me try and write something today to nicely wrap all this

**Comment by Levitanus** [comment]
Actually, as I understood, this function introduced in reaper 5.9 for support calls to win32 api, (from js reaextension and sws br), to not shut reaper down by this calls.

The last couple of days I was trying to make something useful with theese extensions, and failed. But I learned practical need of this api call 😀

**Comment by RomeoDespres** [comment]
Hey, so I've pushed the solution I was talking about. During its writing, I've discovered a new problem: the new version of `rpr_packp` leads to `OSError` being raised whenever calling ReaScript functions on non-valid IDs. Here is an example:

```python
>>> import reapy
>>> t = reapy.Project().add_track()
>>> t.delete()
>>> t.name
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    [...]
    raise DistError(result["traceback"])
reapy.errors.DistError:

An error occurred while running a function inside REAPER. Traceback was :

Traceback (most recent call last):
  File "C:\Users\despres\Desktop\reaper\scripts\reapy\reapy\tools\network\server.py", line 67, in _process_request
    result["value"] = request["function"](*args, **kwargs)
  File "C://Program Files//REAPER (x64)//Plugins\reaper_python.py", line 2082, in RPR_GetTrackName
    r=f(t[0],t[1],t[2])
OSError: exception: access violation reading 0xFFFFFFFFFFFFFFFF
```

I'm not sure how we should handle this. As you've previously mentioned, the performance overhead of checking for all projects in `rpr_packp` is much too high. I can see three options:

1. Leave it as it is now. Problem is that users receive a very unexplicit error, and that the only way they can catch it from the outside is by catching all `DistError` exceptions (which is far too wide).
2. Wrap all ReaScript functions in a `try ... except` block so that they return `None` everytime the error occurs. This behavior is the closest to what ReaScript natively does. Yet it lacks type consistency (good luck with the .pyi files to implement this), and will probably create a bunch of errors everywhere in reapy's code. In the end, users will face unexplicit `AttributeError: 'NoneType' object has no attribute ...`.
3. Wrap all ReaScript functions in a `try ... except` block that raises a special reapy exception (e.g. `InvalidIDError`). From a few tests I've been doing, it would be a 1-2% overhead in performance on all API calls.

Do you have any ideas on this topic?

**Comment by Levitanus** [comment]
I don't like the idea of legal None, but love the conception «fail fast». But the idea of wrapping everything in try-except is not my favorite...

I wonder which arg causes an error and if we can make it on the C-bindings side. I'll check at the night

**Comment by Levitanus** [comment]
Interesting. I can't reproduce this fall on my machine...

It looks like here pointers access is made safer than in Windows version, but now it falls on the next step (string buffer unpacking).

```Python
import reapy as rpr

tr = rpr.Project().add_track()
id_ = tr.id
tr.delete()
print(tr.depth)
print(tr.name)
---------------------------
Traceback (most recent call last):
  File "simple_test.py", line 12, in <module>
    print(tr.name)
  File "/home/levitanus/gits/reapy/reapy/core/track/track.py", line 542, in name
    _, _, name, _ = RPR.GetTrackName(self.id, "", 2048)
  File "/opt/REAPER/Plugins/reaper_python.py", line 2111, in RPR_GetTrackName
    return (r,p0,rpr_unpacks(t[1]),p2)
  File "/opt/REAPER/Plugins/reaper_python.py", line 47, in rpr_unpacks
    return str(v.value.decode())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
```

Actually, I'm confused of how to handle this zoo at the library level.

**Comment by Levitanus** [comment]
I've double-checked all Your fixes and think that for the moment it's the best could be done, as it provides at least good mechanic for making things safe in the particular cases. And then we have just unknown set of exceptions to handle ... somewhere.

Maybe only one thing could be made for convenience: context manager (`safely()` for example) as it made for `make_current_project()`

**Comment by Levitanus** [comment]
How do You think, isn't it enough for now?

**Comment by RomeoDespres** [comment]
Yes I think it is fine that way. Thanks for the feedback about the way Linux behaves with invalid pointers. I don't believe fixing this new issue right now is necessary to merge this PR.

I've changed `Track.index` to be 0-based, so that it is consistent with `project.tracks`:

```python
>>> project = reapy.Project()
>>> track = project.tracks[0]
>>> track == project.tracks[track.index]
True
```

**Pull request merged**
